In [1]:
import numpy as np

In [2]:
arr1= np.array([1,2,3,4,5])

In [3]:
arr2= np.array([1,2,3,4,5])

In [4]:
arr3= arr1 + arr2

In [5]:
print(arr3)

[ 2  4  6  8 10]


In [6]:
np.power(arr1,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [7]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
print(x[1:7:2])

[1 3 5]


In [9]:
values = np.arange(100,200,10)

In [10]:
values = values.reshape(5,2)

In [11]:
values = values.reshape(1,-1)

In [12]:
print(values)

[[100 110 120 130 140 150 160 170 180 190]]


In [13]:
sisi_dadu = [1,2,3,4,5,6]

In [15]:
def all_same(n):
    count = 0
    for i in range(n):
        coin_pertama = np.random.choice(sisi_dadu)
        coin_kedua = np.random.choice(sisi_dadu)
        coin_ketiga = np.random.choice(sisi_dadu)
        
        # mengecek sesuai kondisi yang diinginkan yaitu HHH atau TTT maka:
        if (coin_pertama + coin_kedua + coin_ketiga > 4):
            count += 1
            
    return count / n

In [16]:
all_same(10000)

0.9815